name: Build iOS App and IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Flutter doctor
      run: flutter doctor -v
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS app (no codesign)
      run: flutter build ios --release --no-codesign
    
    - name: Build IPA package
      run: flutter build ipa --release --export-method=ad-hoc --no-codesign
    
    - name: List build artifacts
      run: |
        echo "=== iOS Build Directory ==="
        ls -la build/ios/
        echo "=== IPA Directory ==="
        ls -la build/ios/ipa/ || echo "IPA directory not found"
        echo "=== Runner.app ==="
        ls -la build/ios/iphoneos/ || echo "iphoneos directory not found"
    
    - name: Upload IPA file
      uses: actions/upload-artifact@v3
      with:
        name: zulip-ios-app
        path: build/ios/ipa/*.ipa
        retention-days: 30
    
    - name: Upload Runner.app
      uses: actions/upload-artifact@v3
      with:
        name: zulip-ios-app-bundle
        path: build/ios/iphoneos/Runner.app
        retention-days: 30